#index:
#    path: /
#    controller: App\Controller\DefaultController::index

test:
    path: /api/test
    controller: App\Controller\ApiController::index

api_refresh_token:
    path: /api/token/refresh

api_login_check:
    path: /api/token/login