framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false

App\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        middleName:
            - NotBlank: 
                allowNull: true
        email:
            - Email: ~
        password:
            - NotBlank: ~

App\Entity\Task:
    properties:
        name:
            - NotBlank: ~
        description:
            - NotBlank: ~