framework:
  rate_limiter:
    anonymous_api:
      # use 'sliding_window' if you prefer that policy
      policy: 'fixed_window'
      limit: 300
      interval: '5 minutes'
    authenticated_api:
      policy: 'token_bucket'
      limit: 5000
      rate: { interval: '15 minutes', amount: 500 }
